
# SEO settings
title: "Jonah"
title2: "Liu" # default: ""
description: "JonahLiu's Site for coding, writing"
keywords: "jonahliu, free, download, SEO, blog, web, thinkspace"
url: http://me.jonahliu.cf # site url
baseurl: null # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
disqus_shortname: "heiswayi"
twitter_username: "HeiswayiNrird"
comments: true 

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Jonah Liu"
  job      : "Undergraduate Student at Xiamen University"
  bio      : "Writing and Coding"
  thumb    : /images/author.jpg
  email    : jonahliu@outlook.com
  url      : http://me.jonahliu.cf
  github   : http://github.com/lsforusual
  twitter  : JonahLiu
  facebook : JonahLiu
  linkedin : 

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog
  - slug : Test
    title: Title

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
